version: '3.8'

services:
  db:
    image: postgres:14.2-alpine
    volumes:
      - postgres_data_storage:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=user"
      - "POSTGRES_PASSWORD=fred"
      - "POSTGRES_DB=testdb"
    networks:
      - default

volumes:
  postgres_data_storage:
